<a href="https://colab.research.google.com/github/aru1234/torch-pract/blob/main/Pytorch_Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
scalar = torch.tensor(18)
scalar

tensor(18)

In [ ]:
vector = torch.tensor([4,18])
vector

tensor([ 4, 18])

In [ ]:
matrix = torch.tensor([[2,1],[3,2]])
matrix

tensor([[2, 1],
        [3, 2]])

In [ ]:
print(matrix.ndim)
print(vector.ndim)
print(scalar.ndim)

2
1
0


In [ ]:
print(matrix.shape)
print(vector.shape)
print(scalar.shape)

torch.Size([2, 2])
torch.Size([2])
torch.Size([])


In [ ]:
MATRIX = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]]])
MATRIX

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
print(MATRIX.ndim)
print(MATRIX.shape)
print(MATRIX[0])

3
torch.Size([1, 3, 3])
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


In [ ]:
print(MATRIX[0][2][0])

tensor(7)


In [ ]:
random_tensor = torch.rand(size=(3,4))
random_tensor, random_tensor.dtype

(tensor([[0.5156, 0.5743, 0.3836, 0.3800],
         [0.9462, 0.3814, 0.2397, 0.8319],
         [0.3510, 0.5172, 0.1545, 0.5154]]), torch.float32)

In [ ]:
random_image_size_tensor = torch.rand(224,224,3)
random_image_size_tensor

tensor([[[0.5720, 0.7679, 0.4847],
         [0.5941, 0.0846, 0.1547],
         [0.9049, 0.1304, 0.3689],
         ...,
         [0.4967, 0.4916, 0.5944],
         [0.4833, 0.9479, 0.6499],
         [0.7261, 0.1071, 0.4291]],

        [[0.5990, 0.7455, 0.9303],
         [0.0488, 0.1918, 0.0297],
         [0.1886, 0.6685, 0.6446],
         ...,
         [0.3672, 0.1021, 0.2289],
         [0.8592, 0.8227, 0.4682],
         [0.3945, 0.4627, 0.2642]],

        [[0.0021, 0.6156, 0.0395],
         [0.7911, 0.6408, 0.0713],
         [0.1652, 0.5578, 0.9717],
         ...,
         [0.5857, 0.2554, 0.1973],
         [0.8744, 0.3003, 0.0021],
         [0.8927, 0.8764, 0.4347]],

        ...,

        [[0.6829, 0.8685, 0.3316],
         [0.2014, 0.3944, 0.1210],
         [0.4771, 0.8319, 0.1582],
         ...,
         [0.6349, 0.9182, 0.9153],
         [0.9793, 0.4826, 0.2702],
         [0.6666, 0.9140, 0.3310]],

        [[0.6284, 0.2155, 0.8641],
         [0.9350, 0.7974, 0.3493],
         [0.

In [ ]:
random_image_size_tensor.shape

torch.Size([224, 224, 3])

In [ ]:
random_image_size_tensor[2]

tensor([[0.0021, 0.6156, 0.0395],
        [0.7911, 0.6408, 0.0713],
        [0.1652, 0.5578, 0.9717],
        [0.6491, 0.6039, 0.5319],
        [0.8198, 0.2536, 0.3561],
        [0.9510, 0.9565, 0.8273],
        [0.0841, 0.0935, 0.0131],
        [0.8328, 0.4526, 0.0880],
        [0.5471, 0.2821, 0.9264],
        [0.9139, 0.7587, 0.0467],
        [0.8614, 0.6711, 0.1668],
        [0.2719, 0.9626, 0.4834],
        [0.9567, 0.1659, 0.8568],
        [0.1077, 0.2152, 0.6431],
        [0.4682, 0.3020, 0.3895],
        [0.2811, 0.7768, 0.7626],
        [0.3725, 0.1874, 0.6584],
        [0.4455, 0.0619, 0.7313],
        [0.9318, 0.0506, 0.8957],
        [0.8496, 0.0130, 0.5498],
        [0.1933, 0.0149, 0.3841],
        [0.5849, 0.2296, 0.8923],
        [0.4287, 0.4598, 0.7837],
        [0.6679, 0.7993, 0.9493],
        [0.9387, 0.5827, 0.2472],
        [0.5141, 0.1862, 0.1526],
        [0.2660, 0.8589, 0.1711],
        [0.6977, 0.4569, 0.3934],
        [0.6463, 0.5387, 0.4864],
        [0.151

In [ ]:
random_image_size_tensor.ndim

3

In [ ]:
random_image_size_tensor = torch.rand(size=(3,224,224))
random_image_size_tensor

tensor([[[0.2617, 0.2406, 0.7433,  ..., 0.2927, 0.2642, 0.3442],
         [0.3056, 0.5090, 0.3599,  ..., 0.1889, 0.3666, 0.1728],
         [0.3323, 0.4492, 0.2020,  ..., 0.4498, 0.5064, 0.3891],
         ...,
         [0.3917, 0.2910, 0.2227,  ..., 0.0319, 0.2953, 0.4543],
         [0.1746, 0.4967, 0.8628,  ..., 0.0316, 0.3206, 0.4223],
         [0.5979, 0.2980, 0.7464,  ..., 0.0836, 0.7663, 0.4866]],

        [[0.2443, 0.9165, 0.1657,  ..., 0.8847, 0.9295, 0.4956],
         [0.1738, 0.2226, 0.1628,  ..., 0.9183, 0.9558, 0.8577],
         [0.7225, 0.5153, 0.0626,  ..., 0.0443, 0.6665, 0.6954],
         ...,
         [0.4454, 0.4023, 0.8935,  ..., 0.5735, 0.9941, 0.0103],
         [0.8624, 0.1409, 0.0804,  ..., 0.5293, 0.8449, 0.3134],
         [0.7441, 0.1776, 0.7630,  ..., 0.2348, 0.1600, 0.7252]],

        [[0.4115, 0.3945, 0.3995,  ..., 0.7184, 0.5400, 0.0030],
         [0.3420, 0.0813, 0.3200,  ..., 0.0423, 0.5788, 0.0586],
         [0.2924, 0.2756, 0.2534,  ..., 0.5952, 0.0462, 0.

random_image_size_tensor.shape

In [ ]:
random_image_size_tensor.ndim

3

In [ ]:
random_image_size_tensor[2]

tensor([[0.4115, 0.3945, 0.3995,  ..., 0.7184, 0.5400, 0.0030],
        [0.3420, 0.0813, 0.3200,  ..., 0.0423, 0.5788, 0.0586],
        [0.2924, 0.2756, 0.2534,  ..., 0.5952, 0.0462, 0.1593],
        ...,
        [0.7066, 0.4133, 0.3583,  ..., 0.5998, 0.6568, 0.3801],
        [0.3915, 0.0704, 0.9934,  ..., 0.5087, 0.7528, 0.6215],
        [0.1070, 0.6445, 0.9809,  ..., 0.6365, 0.0288, 0.0051]])

In [ ]:
zeros = torch.zeros(size=(3,4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]), torch.float32)

In [ ]:
ones = torch.ones(size=(2,3))
ones, ones.dtype

(tensor([[1., 1., 1.],
         [1., 1., 1.]]), torch.float32)

In [ ]:
arrange_zero_to_ten = torch.arange(start=0,end=10,step=1)
arrange_zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
ten_zeros = torch.zeros_like(input=arrange_zero_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
float_32_tensor = torch.tensor([3.0,6.0,9.0], dtype=None, device=None, requires_grad = False)
float_32_tensor, float_32_tensor.dtype, float_32_tensor.device

(tensor([3., 6., 9.]), torch.float32, device(type='cpu'))