<a href="https://colab.research.google.com/github/aru1234/torch-pract/blob/main/pytorch_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
tensor * 10

tensor([10, 20, 30])

In [ ]:
tensor - 10

tensor([-9, -8, -7])

In [ ]:
tensor / 10

tensor([0.1000, 0.2000, 0.3000])

In [ ]:
tensor.multiply(10)

tensor([10, 20, 30])

In [ ]:
tensor.add(10)

tensor([11, 12, 13])

In [ ]:
tensor.sub(10)

tensor([-9, -8, -7])

In [ ]:
tensor * tensor

tensor([1, 4, 9])

In [ ]:
torch.matmul(tensor,tensor)

tensor(14)

In [ ]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 1.25 ms, sys: 0 ns, total: 1.25 ms
Wall time: 1.27 ms


tensor(14)

In [ ]:
%%time
# Matrix multiplication by hand 
# (avoid doing operations with for loops at all cost, they are computationally expensive)
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
value

CPU times: user 1.64 ms, sys: 0 ns, total: 1.64 ms
Wall time: 3.77 ms


tensor(14)

In [ ]:
tensor_A = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
tensor_B = torch.tensor([[10,11,12],[13,14,15],[16,17,18]])
tensor_A @ tensor_B


tensor([[ 84,  90,  96],
        [201, 216, 231],
        [318, 342, 366]])

In [ ]:
tensor_C = torch.tensor([[1,2],[3,4],[5,6]])
tensor_D = torch.tensor([[7,8],[9,10],[11,12]])

print(tensor_C.shape)
print(tensor_D.shape)
print(tensor_D.T.shape)

print(tensor_C @ tensor_D.T)



torch.Size([3, 2])
torch.Size([3, 2])
torch.Size([2, 3])
tensor([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])


In [ ]:
x = torch.arange(1,11,1)
torch.min(x), x.min()

(tensor(1), tensor(1))

In [ ]:
torch.max(x) , x.max()

(tensor(10), tensor(10))

In [ ]:
torch.mean(x,dtype=torch.float32), x.mean(dtype=torch.float32)

(tensor(5.5000), tensor(5.5000))